spring:
  application:
    name: DEMO-SERVICE # ==> This is Service-Id


---
# Items that apply to ALL profiles:
eureka:
  instance:
    appname: DEMO-SERVICE  # ==> This is a instance of DEMO-SERVICE
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8000

---
spring:
  profiles: demo-service-replica01
eureka:
  instance:
    appname: DEMO-SERVICE  # ==> This is a instance of DEMO-SERVICE
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8001

---
spring:
  profiles: demo-service-replica02
eureka:
  instance:
    appname: DEMO-SERVICE  # ==> This is a instance of DEMO-SERVICE
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8002

---
spring:
  profiles: demo-service-replica03
eureka:
  instance:
    appname: DEMO-SERVICE  # ==> This is a instance of DEMO-SERVICE
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8003

---
spring:
  profiles: demo-service-replica04
eureka:
  instance:
    appname: DEMO-SERVICE  # ==> This is a instance of DEMO-SERVICE
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8004

---
spring:
  profiles: demo-service-replica05
eureka:
  instance:
    appname: DEMO-SERVICE  # ==> This is a instance of DEMO-SERVICE
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8005