server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

spring:
  application:
    name: eureka-server

---
spring:
  profiles: demo-server-replica01
  application:
    name: eureka-server-clustered   # ==> This is Service-Id
server:
  port: 9001
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:9002/eureka/,http://localhost.com:9003/eureka/

---
spring:
  profiles: demo-server-replica02
  application:
    name: eureka-server-clustered   # ==> This is Service-Id
server:
  port: 9002
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/,http://localhost:9003/eureka/

---
spring:
  profiles: demo-server-replica03
  application:
    name: eureka-server-clustered    # ==> This is Service-Id
server:
  port: 9003
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/,http://localhost:9002/eureka/